name: ci

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1


jobs:

  core:
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-26.04, macos-latest]
        python_version: ['3.14']
        include:
          - os: ubuntu-26.04
            python_version: '3.10'

    runs-on: ${{ matrix.os }}

    steps:

    - name: "astrometry.net (Linux)"
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends astrometry.net

    - name: "astrometry.net (macOS)"
      if: runner.os == 'macOS'
      run: brew install astrometry-net

    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python_version }}

    - run: pip install .[tests]

    - run: |
        pip install mypy
        mypy
      if: ${{ matrix.python_version == '3.14' && matrix.os == 'ubuntu-latest' }}

    - name: download index data
      run: python -m astrometry_azel.download -source https://data.astrometry.net/4100/ -i 10 15

    - run: pytest
